### ISSUE TITLE
Mensagens

### ISSUE THREAD

**Issue by laisbastosbg** [Luizerz/PassGen#1]
Sugiro deixar as mensagens mais limpas, apesar de estarem muito bonitas, as mensagens podem acabar se perdendo no meio de tanta informação

https://github.com/Luizerz/PassGen/blob/00081fcafdd78fda81c1e15a9ff9d54976276d54/Sources/PassGenLibrary/strings.swift#L9-L21

**Comment by Luizerz** [comment]
Opa Lais, obgd pela sugestão, irei super levar em consideração, anotado xD.
