### ISSUE TITLE
Muito massa!

### ISSUE THREAD

**Issue by Thaynara-Andrade** [Luizerz/PassGen#10]
**Primeiramente gostaria de parabenizar você pelo seu trabalho e por toda a ajudada que deu aos outros projetos também.**

_Uma ideia seria associar as senhas geradas com dados importantes para as pessoas que estão solicitando, assim fica mais fácil de lembrar, e conseguimos embaralhar com sinais especiais._

**Isso me lembra que tenho que trocar todas as minhas senhas urgentes, parabéns amigo ficou muito bom o código! Um abraço <3**

**Comment by Luizerz** [comment]
Obrigado pelo feedback Thay 🥰, sua consideração é super valida, agradeço muito e deixe sempre sua senhas seguras <3
