### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by nillias** [Luizerz/PassGen#11]
https://github.com/Luizerz/PassGen/blob/00081fcafdd78fda81c1e15a9ff9d54976276d54/README.md?plain=1#L1-L9

Oi Luiz, muito massa seu projeto. Eu só consigo usar ele no mac? Estava precisando de um gerador de senhas rs. 
Queria saber também que ferramenta você utilizou pra colocar o nome do seu projeto dessa forma que destaquei.

**Comment by Luizerz** [comment]
Eae Nillia ☺️, obrigado pelo comentário, o projeto ele funciona tranquilamente em qualquer outro sistema operacional, basta instalar ele pelo `brew`(ele é um gerenciador de pacotes, https://brew.sh) ou apenas dar um `swift run` pelo terminal em um Sistema Operacional que tenha instalado o Swift.
E o Site que eu utilizei para fazer essas letras foi o https://patorjk.com/software/taag/#p=display&f=Ogre&t=Type%20Something%20
