### ISSUE TITLE
Desacoplando e criando função 

### ISSUE THREAD

**Issue by Robsonmxms** [Luizerz/PassGen#2]
https://github.com/Luizerz/PassGen/blob/00081fcafdd78fda81c1e15a9ff9d54976276d54/Sources/PassGenLibrary/passwordSt.swift#L42-L56

Você pode desacoplar esse trecho de código e criar uma função própria para que seja chamada dentro do else

**Comment by Luizerz** [comment]
Eae Robson, muito obrigado pelo comentário, faz total sentido desacoplar essa parte do código, muito bem apontado. Irei adaptar o mais rápido possível vlww 😆.
