### ISSUE TITLE
Paradigmas

### ISSUE THREAD

**Issue by JoanWilson** [Luizerz/PassGen#3]
Eu amei seu código e seu programa em si, pois é algo que eu preciso diariamente. Uma sugestão foi com a organização do paradigma do código, pois eu vi algumas Struct e um arquivo chamado functions. Você poderia colocar todo o seu código como Programação Orientada a Protocolos e criar structs para cada classe, bem como os seus respectivos métodos.

**Comment by Luizerz** [comment]
Eae Wilson, obrigado pelo comentário, irei levar em consideração e pesquisar um pouco mais sobre protocolos e ver como melhorar o paradigma do código, é realmente algo que eu posso melhorar 😆.
