### ISSUE TITLE
Comentário sobre o programa✨

### ISSUE THREAD

**Issue by SarahMadalena** [Luizerz/PassGen#5]
Eu achei muito criativa a proposta do programa, aquele jeito de escrever o nome do programa no README e a forma como as messages são printadas também (me ensina😝). Além disso, gostaria de saber o que são essas @Options.

**Comment by Luizerz** [comment]
Eae Sarinha 😝, muito feliz que você tenha gostado, os textos que tem tanto no README quanto no nas mensagens que são printadas no terminal são feitas por geradores ASCII. Irei disponibilizar o link [AQUI.](https://www.coolgenerator.com/ascii-text-generator)  
Agora falando sobre a parte dos `@options` pode ser um pouco extenso mas prometo que vou tentar fazer você entender, então se prepare kkkkk  
  
Primeiramente eu preciso dizer que eu usei um package chamado ArgumentParser, ele funciona passando parâmetro na própria linha do terminal.  
O `@Option` é um elemento que esse package fornece, ele é basicamente como um `readLine()` com tratamento, exemplo:
```swift
@Option(name: NameSpecification.shortAndLong, help: "Name to be assigned to password")
    var pass_name: String      //Variavel em que o input do @Option vai colocar 
```
O que está acontecendo é o seguinte, esse `@Option` em especifico, recebe um input do usuário do tipo String e para chamar esse `@Option` é necessário passar o seguinte parâmetro no terminal :  
```cmd
passgen -pass_name <String> // ou
passgen -p    
//observe que existe apenas 1 parâmetro nesse exemplo, mas o código em si tem 2 ( logo, existe 2 @Option)  
passgen -s <Int> -p <String>
```  
os parâmetros `name: NameSpecification.shortAndLong` e `help: "Name to be assigned to password"` , fazem respectivamente o seguinte. Permite o usuário de declarar a tag sendo `passgen -p` ou `passgen --pass_name` (que seria uma forma curta ou longa de mostrar a tag do argumento). E o segundo é basicamente o "tratamento de erro" já que caso o usuário digite um valor que não se encaixe ou não digite a tag ele ira retornar a forma de uso e também o que a tag recebe e faz.  
<img width="419" alt="Captura de Tela 2022-04-01 às 09 24 12" src="https://user-images.githubusercontent.com/75648725/161262633-300f835e-08ff-4d36-88f0-70b95613637c.png">  
<img width="491" alt="Captura de Tela 2022-04-01 às 09 25 13" src="https://user-images.githubusercontent.com/75648725/161262825-3bc1973b-8801-4802-a7ff-872efe0fe176.png">  
  
Espero que tenha dado pra entender um pouco, qualquer outra duvida ou se quiser se aprofundar mais o no uso desse package você pode vir falar comigo 😆.
