### ISSUE TITLE
Sugestão de melhoria.

### ISSUE THREAD

**Issue by reserved1** [Luizerz/PassGen#6]
https://github.com/Luizerz/PassGen/blob/00081fcafdd78fda81c1e15a9ff9d54976276d54/Sources/PassGenLibrary/passwordSt.swift#L28-L58

Oi oi Luizerz. uma pequena possível contribuição seria alterar esse começo para ser chamada via função, removendo esse `while` externo.

o código não sei se ta o mais otimizado, mas ficaria basicamente assim(lembra de mudar esse nomes que coloquei kk):

<img width="667" alt="image" src="https://user-images.githubusercontent.com/74558455/161141089-eab21a9d-3838-4c68-b69e-baabfb9dd148.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/74558455/161141176-e8a2a58d-c362-4ee5-88cf-559e548cb219.png">

**Comment by Luizerz** [comment]
Primeiro obrigado pela paciencia de analisar o código xD. Pode deixa Alves anotado. É realmente um ponto muito bom e esses exemplos vao acelerar ainda mais a melhoria do código.
