### ISSUE TITLE
Feedback do programa

### ISSUE THREAD

**Issue by lvasantos** [Luizerz/PassGen#8]
Esse programa é show✨

Os arquivos bem separados e a legibilidade do código tá ótima. Ele guardar as senhas em um arquivo é um extra muito massa !

Parabens !

**Comment by Luizerz** [comment]
Obrigado pelo feedback Luciana, fico extremamente feliz que tenha gostado. Caso haja qualquer duvida sobre o código, basta vir falar comigo ou comentar aqui mesmo  🙃.
