### ISSUE TITLE
Sugestão: Criptografar arquivo senhas.txt

### ISSUE THREAD

**Issue by otavioalbucosta** [Luizerz/PassGen#9]
Bom dia Luiz, beleza?

Uma sugestão de feature que eu gostaria de dar para se implementar posteriormente é a de criptografar o arquivo senhas.txt.
Caso mantenha esse aquivo em .txt, ele fica vulnerável a acessos indesejados e poderia até ter seus conteúdos vazados. Uma sugestão para evitar isso é utilizar a própria biblioteca da Apple de criptografia, segue documentação:

https://developer.apple.com/documentation/applearchive/encrypting_and_decrypting_a_single_file

**Comment by Luizerz** [comment]
Obrigado pelo feedback Otavio, sua sugestão é bem válida, muito provavelmente quando for mexer novamente no código desse projeto irei tentar dar uma bela olhada nessa documentação e tentar implementar em meu código. xD
